# Use an official Node runtime as the base image
FROM node:18-bullseye

# Set the working directory in the container
WORKDIR /storybook

# Install xdg-utils
RUN apt-get update && apt-get install -y xdg-utils